/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class Engine {
  constructor(modelPath: string)
  transcribe(audioFile: string): string
  samplingRate(): number
}
